services:
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - "5173:5173"
    container_name: electric-frontend
    command: pnpm vite dev
    environment:
      - PORT=5173
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend/
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - "3000:3000"
    container_name: electric-backend
    command: pnpm run start:dev
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - API_URL=${API_URL}
    depends_on:
      - electric-db

  #================= Database =================

  electric-db:
    image: postgres:17.0-alpine
    ports:
      - "6000:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
