services:
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - "5173:5173"
    container_name: electric-frontend
    command: pnpm run dev --host
    environment:
      - PORT=5173
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://backend:3000/api/v1/balance
    depends_on:
      - backend

  backend:
    build: ./backend/
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - "3000:3000"
    container_name: electric-backend
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - API_URL=${API_URL}
    depends_on:
      electric-db:
        condition: service_healthy

  #================= Database =================

  electric-db:
    image: postgres:17.0-alpine
    ports:
      - "6000:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
